name: release-build
on:
  workflow_dispatch
jobs:
  build-jar:
    name: build java executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt
          cache: gradle
      - name: Get Version Number
        run: >
          echo "VERSION=$(./gradlew properties -q | grep "runnerVersion:" | awk
          '{print $2}')" >> $GITHUB_ENV
      - name: build JAR
        run: ./gradlew clean build
      - name: upload release assert
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: build/quarkus-app/quarkus-run.jar
          asset_name: 'command-runner-${{env.VERSION}}-all.jar'
          asset_content_type: application/octet-stream
  build:
    name: Build with GraalVM on macos-latest
    runs-on: macos-latest
    steps:
      - name: download latest cli
        run: >-
          curl
          https://repo1.maven.org/maven2/org/openapitools/openapistylevalidator/openapi-style-validator-cli/1.8/openapi-style-validator-cli-1.8-all.jar
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm-version: 21.3.0.java17
      - name: Install native-image
        run: gu install native-image
      - name: Build native executable
        run: native-image -jar openapi-style-validator-cli-1.8-all.jar
      - name: Upload native executable
        id: upload-native-executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: openapi-style-validator-cli-1.8-all
          asset_name: openapi-style-validator-cli-1.8-mac-latest
          asset_content_type: application/octet-stream
